### ISSUE TITLE
CFG error at LOOP_LEFT

### ISSUE THREAD

**Issue by jormal** [kupl/MicSE#13]
# Bug Report

## Symptom

- Output node of `LOOP_LEFT` is in the wrong place.

## Scenario and Screenshot

- [Code](/kupl/MicSE/blob/master/benchmarks/toy/looptest_loop_left.tz)
```
parameter (list string);
storage (list string);
code { CAR; NIL string; SWAP; PAIR; LEFT (list string);
       LOOP_LEFT { DUP; CAR; DIP{CDR};
                   IF_CONS { SWAP; DIP{CONS}; PAIR; LEFT (list string) }
                           { RIGHT (pair (list string) (list string)) }; };
       NIL operation; PAIR }
```

- Screenshot
![graphviz (7)](https://user-images.githubusercontent.com/13883175/103461806-6a466a00-4d64-11eb-9c71-05c7877562ee.png)

Vertex #56 is in the wrong place. I think Vertex #56 should be in between #17 and #19.

## Reference

- [Michelson-reference #instr-LOOP_LEFT](https://tezos.gitlab.io/michelson-reference/#instr-LOOP_LEFT)

**Comment by cushionbadak** [comment]
I guess the vertex-56 should be placed between vtx-22 and vtx-17 to update `v3`. I'll check the reason soon.

**Comment by cushionbadak** [comment]
The problem comes from the vertex-concatenation. `t_con_vtx_back acc_in_v (...)` in line-1536 constructs `vtx-56 -> vtx-22` edge. Replacing it to `PreLib.Cfg.t_con_vtx_front` fixes this issue by constructing `vtx-22 -> vtx-56` edge, and this results to connect `vtx-56 -> vtx-17` edge too.
https://github.com/kupl/MicSE/blob/6df4d566011cd4e928896f96ab6bd14651f65123/src/pre/translator.ml#L1534-L1536
![issue13_solved](https://user-images.githubusercontent.com/10959858/103469724-a9e47480-4dab-11eb-9e0b-d8e958bd8ed8.png)
